{% set name = "fcd" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FCD-{{ version }}.tar.gz
  sha256: 6cc56a5c9d4ec6d6ee480b3ed94d858ba8d6d20db70319ff802c51737d166e32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - keras
    - numpy
    - python
    - scipy
    - tensorflow
    - rdkit

test:
  imports:
    - fcd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bioinf-jku/FCD
  summary: Fréchet ChEMNet Distance
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
