{% set name = "fcd" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c76735ed2aba248a54425430cfe95e42c760a8d498c275dbf65a050492fb62fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - keras
    - numpy
    - python
    - scipy
    - tensorflow
    - rdkit

test:
  imports:
    - fcd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bioinf-jku/FCD
  summary: Fréchet ChEMNet Distance
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
