{% set name = "fcd" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf59edbfc90dc9eea07a820de1eaa329075c23876ceaf34656823dbe128f5a74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - keras
    - numpy
    - python
    - scipy
    - tensorflow
    - rdkit

test:
  imports:
    - fcd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bioinf-jku/FCD
  summary: Fréchet ChEMNet Distance
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
